# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c883e90603d6be26244cc5ad1bfcecd1059bf77b697d027dd5daf57a363c86fbff0e6c2d8ad08edafc99654db2a89c6054a4d3b90ef0e3ff97f5ee03e4ca2329

test:
  secret_key_base: de9914b29adf3bbe437f1776da9eb5603a801a496a9c9b7990cd55b0609bf4830d51d5eb208c140990b792075953e304894f04c1208826bb574fad1490437425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
